AgiSoft/Controllers/ProductController.cs
/***********************************************************************************************
************************************************************************************************
* <author>Ralph Bohn & Harshad Deshmukh</author>                                               *
* <email>info@cueowl.com</email>                                                               *
* <date>2013-06-01</date>                                                                      *
* <file>ProductController.cs</file>                                                            *
* <summary>Contains the Controller methods for Product in MVC framework.                       *
*      Controls the product info for AgiSoft</summary>                                         *
************************************************************************************************      
************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgiSoft.Models;
using System.Data;

namespace AgiSoft.Controllers {
    public class ProductController : Controller {
        // Fields
        CueDb db = new CueDb();


        // GET: /Product
        public ActionResult Index() {
            return View();
        }
        
        // GET: /Product/Features/
        public ActionResult Features() {
            return View();
        }

        // GET: /Product/Pricing/
        public ActionResult Pricing() {
            return View();
        }

        // GET: /Product/Support/
        public ActionResult Support() {
            return View();
        }

        // GET: /Product/Order/
        public ActionResult SignUp() {
            return View();
        }

        // GET: /Product/Admin
        [Authorize(Roles="CueOwl")]
        public ActionResult Admin() {
            return View(db.Products.ToList());
        }

        // GET: /Product/Details/5
        [Authorize(Roles = "CueOwl")]
        public ActionResult Details(int id=0) {
            Products products = db.Products.Find(id);
            if (products == null) {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: /Product/Create
        [Authorize(Roles = "CueOwl")]
        public ActionResult Create() {
            
            return View();
        }

        // POST: /Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "CueOwl")]
        public ActionResult Create(Products products) {
            if (ModelState.IsValid) {
                db.Products.Add(products);
                db.SaveChanges();
                return RedirectToAction("Admin");
            }

            return View(products);
        }

        // GET: /Product/Edit/5
        [Authorize(Roles = "CueOwl")]
        public ActionResult Edit(int id) {
            Products products = db.Products.Find(id);
            if (products == null) {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: /Product/Edit/5
        [HttpPost]
        [Authorize(Roles = "CueOwl")]
        public ActionResult Edit(Products products) {
            if (ModelState.IsValid) {
                db.Entry(products).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Admin");
            }
            return View(products);
        }

        // GET: /Product/Delete/5
        [Authorize(Roles = "CueOwl")]
        public ActionResult Delete(int id=0) {
            Products products = db.Products.Find(id);
            if (products == null) {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: /Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "CueOwl")]
        public ActionResult DeleteConfirmed(int id) {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Admin");
        }

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AgiSoft/Controllers/ProjMgrController.cs
/***********************************************************************************************
************************************************************************************************
* <author>Ralph Bohn & Harshad Deshmukh</author>                                               *
* <email>info@cueowl.com</email>                                                               *
* <date>2013-06-01</date>                                                                      *
* <file>ProjMgrController.cs</file>                                                            *
* <summary>Contains the Controller methods for Project Manager in MVC framework.               *
*      All the Project Manager Functionality 'controlled' thru here</summary>                  *
************************************************************************************************      
************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgiSoft.Controllers {
    [Authorize]
    public class ProjMgrController : Controller {
        //
        // GET: /ProjMgr/

        public ActionResult Index() {
            return View();
        }

    }
}

AgiSoft/Views/Shared/_AppLayout.cshtml
@{ViewBag.MyLayout = "App";}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>AgiSoft- Agile Project Management Solutions</title>
        <link href="~/CueIcon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/appcss")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="toptoolbar">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("AgiSoft logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Overview", "Index", "Product")</li>
                            <li>@Html.ActionLink("Details", "Features", "Product")</li>
                            <li>@Html.ActionLink("Plans/Prices", "Pricing", "Product")</li>
                            <li>@Html.ActionLink("Support", "Support", "Product")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            <section class="clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; 2012 - CueOwl,llc</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

AgiSoft/Views/Shared/_Dashboard.cshtml
<section class="dashboard">
    <div class="dashinfo">
        <h1>This is dashboard area</h1>
    </div>
</section>

AgiSoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>AgiSoft- Agile Project Management Solutions</title>
        <link href="~/CueIcon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")   
    </head>
    <body>
        <header>
            <div class="toptoolbar">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
            </div>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Sprint", "Index", "Sprint")</li>
                            <li>@Html.ActionLink("Team", "Index", "Team")</li>
                            <li>@Html.ActionLink("Proj Mgr", "Index", "ProjMgr")</li>
                            <li>@Html.ActionLink("Assignment", "Index", "Assignment")</li>
                            <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                            <li>@Html.ActionLink("Account", "Index", "Account")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @Html.Partial("_Dashboard")
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; 2012 CueOwl,llc</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>