AgiSoft/ViewModels/TeamViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace AgiSoft.Models {
    public class TeamViewModel {
        // Fields
        private AgiSoftDb db;

        // Constructor
        public TeamViewModel(Teams team) {
            Team = team;
            SetMemberList(Team.SettingId);
            TeamNm = Team.TeamName;
        }

        public TeamViewModel() {

        }

        // Properties
        [Required]
        [Display(Name="Team Name: ")]
        public string TeamNm { get; set; }

        [Required]
        [Display(Name="Member Name: ")]
        public string MemNm { get; set; }

        public Teams Team { get; set; }
        public List<UserProfile> Member { get; set; }

        // Commands
        public void AddMemberToTeam() {
            using (db = new AgiSoftDb()) {

                Teams t = db.Teams.First(x => x.TeamName == TeamNm);
                UserProfile member = db.UserProfiles.First(x => x.UserName == MemNm);
                UsersOnTeam uot = new UsersOnTeam();

                uot.TeamId = t.TeamId;
                uot.UserId = member.UserId;


                try {
                    db.UsersOnTeam.Add(uot);
                    db.SaveChanges();
                } catch (Exception e) {
                    e.ToString();
                    throw e;
                }
            }

        }

        private void SetMemberList(int id) {
            using (db = new AgiSoftDb()) {
                if (Member == null) {
                    Member = new List<UserProfile>();
                }
                Member = db.UserProfiles.Where(x => x.SettingId == id).ToList();
            }
        }

        // Queries
        public List<Teams> GetTeams(int settingId) {
            using (db=new AgiSoftDb()){
                return db.Teams.Where(x=>x.SettingId==settingId).ToList();
            }
        }
        public List<UserProfile> GetMembers(int settingId) {
            //TODO: modify this to only return members belonging to team level and child teams

            using (db = new AgiSoftDb()) {
                return db.UserProfiles.Where(x => x.SettingId == settingId).ToList();
            }
        }
    }
}

AgiSoft/Controllers/AssignmentController.cs
/***********************************************************************************************
************************************************************************************************
* <author>Ralph Bohn & Harshad Deshmukh</author>                                               *
* <email>info@cueowl.com</email>                                                               *
* <date>2013-06-01</date>                                                                      *
* <file>AssignmentController.cs</file>                                                         *
* <summary>Contains the Controller methods for Assignment in MVC framework.                    *
*      Used to [CRUD] assignments and assign to users and track status</summary>               *
************************************************************************************************      
************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgiSoft.Controllers {
    [Authorize]
    public class AssignmentController : Controller {
        
        // GET: /Assignment/
        public ActionResult Index() {
            return View();
        }

        // GET: /Assignment/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: /Assignment/Create
        public ActionResult Create() {
            return View();
        }

        // POST: /Assignment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) {
            try {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }

        // GET: /Assignment/Edit/5
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: /Assignment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection) {
            try {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }

        // GET: /Assignment/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: /Assignment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            try {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            } catch {
                return View();
            }
        }
    }
}

AgiSoft/Controllers/TeamController.cs
/***********************************************************************************************
************************************************************************************************
* <author>Ralph Bohn & Harshad Deshmukh</author>                                               *
* <email>info@cueowl.com</email>                                                               *
* <date>2013-06-01</date>                                                                      *
* <file>TeamController.cs</file>                                                               *
* <summary>Contains the Controller methods for Team in MVC framework.                          *
*      [CRUD] for team members and other functions at team level</summary>                     *
************************************************************************************************      
************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using AgiSoft.Models;

namespace AgiSoft.Controllers {
    [Authorize]
    public class TeamController : Controller {
        private AgiSoftDb db = new AgiSoftDb();
        private int uid = 0;
        private int usetting = 0;


        // GET: /Team/
        public ActionResult Index() {
            return View(db.Teams.ToList());
        }

        // GET: /Team/Member
        public ActionResult Member() {
            uid = WebSecurity.GetUserId(User.Identity.Name);

            Teams t = db.Teams.Find(uid);
            
            return View(db.UsersOnTeam.Where(x=>x.TeamId == t.TeamId).ToList());
        }

        // GET: /Team/MemberTeams
        public ActionResult MemberTeams(int id) {
            Teams t = db.Teams.Find(id);
            TeamViewModel tvm = new TeamViewModel(t);


            return View(tvm);
        }

        // GET: /Team/TeamProject/
        public ActionResult TeamProject() {
            
            return View();
        }

        // POST: /Team/TeamProject
        [HttpPost]
        public ActionResult TeamProject(int id, TeamOnProject model) {
            model.ProjectId = id;
            db.TeamOnProject.Add(model);
            db.SaveChanges();

            return View("Index");
            //return RedirectToAction("Project", "Projects");
        }

        // GET: /Team/Admin/
        public ActionResult Admin() {
            uid = WebSecurity.GetUserId(User.Identity.Name);
            usetting = db.UserProfiles.First(x => x.UserId == uid).SettingId;

            var proj = db.Projects.Where(x => x.Status == 3).Where(v=>v.SettingId == usetting);
            
            Projects prj = new Projects() { ProjectId = 0, ProjectNum = "0", ProjectName = "--Select--" };
            
            List<Projects> ProjList = new List<Projects>();
            ProjList.Add(prj);

            foreach (var pr in proj) {
                prj = new Projects() { ProjectId = pr.ProjectId, ProjectNum = pr.ProjectNum, ProjectName = pr.ProjectName };
                ProjList.Add(prj);
            }

            ViewBag.ProjectId = new SelectList(ProjList, "ProjectId", "ProjectName");

            var teamitem = from p in db.Teams
                           select p;

            TeamOnProject modelteam = new TeamOnProject();
            List<Teams> team = new List<Teams>();

            Teams team1 = new Teams() { TeamId = 0, TeamName = "--Select--" };
            team.Add(team1);
            foreach (var item1 in teamitem) {
                team1 = new Teams() { TeamId = item1.TeamId, TeamName = item1.TeamName };
                team.Add(team1);
            }

            ViewBag.teamId = new SelectList(team, "TeamId", "TeamName", modelteam.TeamId);

            return View();
        }

        // POST: /Team/Admin
        [HttpPost]
        public ActionResult Admin(TeamOnProject model) {
            TeamOnProject t = new TeamOnProject();
            t.ProjectId = model.ProjectId;
            t.TeamId = model.TeamId;
            db.TeamOnProject.Add(t);
            db.SaveChanges();

            return View("Index");
            //return RedirectToAction("Project", "Projects");
        }

        // GET: /Team/Assignment
        public ActionResult Assignment() {
            return View();
        }

        // GET: /Team/Teams
        public ActionResult Teams() {
            return View(db.Teams.ToList());
        }

        // GET: /Team/TeamsDetails
        public ActionResult TeamsDetails(int id = 0) {
            Teams teams = db.Teams.Find(id);

            if (teams == null) {
                return HttpNotFound();
            }
            if (teams != null) {
                ViewBag.Type = "team";
            }

            return View(teams);
        }

        // GET: /Team/TeamsCreate
        public ActionResult TeamsCreate() {
            return View();
        }

        // POST: /Team/TeamsCreate/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TeamsCreate(Teams teams) {
            if (ModelState.IsValid) {
                var u = db.UserProfiles.First(x=>x.UserName == User.Identity.Name);
                teams.SettingId = u.SettingId;
                db.Teams.Add(teams);
                db.SaveChanges();

                return RedirectToAction("Teams");
            }
            return View(teams);
        }

        // GET: /Team/TeamsEdit
        public ActionResult TeamsEdit(int id) {
            Teams teams = db.Teams.Find(id);
            teams.TeamCode = "";

            if (teams == null) {
                return HttpNotFound();
            }

            if (teams != null) {
                ViewBag.Type = "team";
            }

            return View(teams);
        }

        // POST: /Team/TeamsEdit/5
        [HttpPost]
        public ActionResult TeamsEdit(Teams teams) {
            if (ModelState.IsValid) {
                db.Entry(teams).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Teams");
            }

            return View(teams);
        }

        // GET: /Team/Delete
        public ActionResult Delete(int id = 0) {
            Teams teams = db.Teams.Find(id);
            if (teams == null) {
                return HttpNotFound();
            }
            else {
                db.Teams.Remove(teams);
                db.SaveChanges();
                return RedirectToAction("Teams");
            }
            return View(teams);
        }

        // POST: /Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Teams teams = db.Teams.Find(id);
            db.Teams.Remove(teams);
            db.SaveChanges();
            return RedirectToAction("Teams");
        }
    }
}

AgiSoft/Views/Team/Admin.cshtml
@model AgiSoft.Models.TeamOnProject
@{
    ViewBag.Title = "TeamProject";
}

<h2>TeamProject</h2>
<nav>
    <ul id="menu">
        <li>@Html.ActionLink("Index", "Index", "Team")</li>
        <li>@Html.ActionLink("Member", "Member", "Team")</li>
        <li>@Html.ActionLink("Team Projects", "TeamProject", "Team")</li>
        <li>@Html.ActionLink("Assignments", "Assignment", "Team")</li>
    </ul>
</nav>

@using (Html.BeginForm()){
    
    Html.AntiForgeryToken();
    Html.HiddenFor(model => model.ProjectId);
    Html.HiddenFor(model => model.TeamId);
    
    <span>Project Name:</span>
    <div class="editor-label">
        @Html.DropDownListFor(model => model.ProjectId, (SelectList)ViewBag.ProjectId)
        @Html.ValidationMessageFor(model=>model.ProjectId)
    </div>
    <div class="editor-field">
        @Html.DropDownListFor(model => model.TeamId, (SelectList)ViewBag.teamid, new { style = "width:250px" })
        @Html.ValidationMessageFor(model => model.TeamId)
    </div>
    <div>
        <input type="submit" id="assign" value="Assign" name="Assign" />
    </div>
}

AgiSoft/Views/Team/Index.cshtml
@model List<AgiSoft.Models.Teams>

@{
    ViewBag.Title = "Index";
}

<h2>Team page</h2>
<nav>
    <ul id="menu">
        <li>@Html.ActionLink("Index", "Index", "Team")</li>
        <li>@Html.ActionLink("Member", "Member", "Team")</li>
        <li>@Html.ActionLink("Team Projects", "TeamProject", "Team")</li>
        <li>@Html.ActionLink("Assignments", "Assignment", "Team")</li>
    </ul>
</nav>
<ul>
    <li>
        This will display overview at team level. "Team" can be hierarchical.
        <ul>
            <li>overview: members</li>
            <li>overview: projects</li>
            <li>overview: team member assignments and status (based on role)</li>
        </ul>
    </li>
    <li>
        Links to user/team based controls
        <ul>
            <li>Link to PM area</li>
            <li>Link to Sprint Area</li>
        </ul>
    </li>
    <li>
        Team admin functions (based on role)
        <ul>
            <li>[CRUD] for Team members</li>
            <li>[CRUD] for member assignments</li>
        </ul>
    </li>
</ul>
<br />
<h2>Teams</h2>

<p>
    @Html.ActionLink("Create Team", "TeamsCreate")
</p>

<table style="width: 100%;">
    <tr>
        <td style="width: 50%;">
            <table>
                <tr>
                    <th>Team Names:
                    </th>
                    <th>Team Desc:</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(rName => item.TeamName)
                        </td>
                        <td>
                            @Html.DisplayFor(rName => item.TeamDesc)
                        </td>
                        <td>
                            @Html.ActionLink("Edit Teams", "TeamsEdit", new { id = item.TeamId }) |
                            @Html.ActionLink("Team Details", "TeamsDetails", new { id = item.TeamId }) |                        
                            @Html.ActionLink("Delete Team", "Delete", "Team", new { id = item.TeamId }, new { id = item.TeamId, onclick = "return confirm('Are you sure you wish to delete this?')" })
                        </td>
                        <td>
                            @Html.ActionLink("Add Member To Team", "MemberTeams", new {id=item.TeamId})
                        </td>
                    </tr>
                }

            </table>
        </td>
    </tr>
</table>

AgiSoft/Views/Team/Member.cshtml
@model List<AgiSoft.Models.UsersOnTeam>

@{
    ViewBag.Title = "Member";
}

<h2>Member</h2>
<nav>
    <ul id="menu">
        <li>@Html.ActionLink("Index", "Index", "Team")</li>
        <li>@Html.ActionLink("Member", "Member", "Team")</li>
        <li>@Html.ActionLink("Team Projects", "TeamProject", "Team")</li>
        <li>@Html.ActionLink("Assignments", "Assignment", "Team")</li>
    </ul>
</nav>

<ul>
    <li>
        View team members
        <ul>
            <li>
                at team level
            </li>
            <li>
                view member info
            </li>
        </ul>
    </li>
    <li>
        admin functions
        <ul>
            <li>
                add/delete members on team (functions are only team related and not system)
            </li>
            <li>
                edit member
            </li>
            <li>
                other admin stuff
            </li>
        </ul>
    </li>
    <li>
        member can edit profile
    </li>
</ul>
<br />
<h2>Members on your team</h2>

<table style="width: 100%;">
    <tr>
        <td style="width: 50%;">
            <table>
                <tr>
                    <th>Member Names:
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(mem => item.UserProfile.UserName)
                        </td>
                        
                        <td>
                            @Html.ActionLink("Member Details", "MemberDetails", new { id = item.UserId })
                        </td>
                        <td>
                            @Html.ActionLink("Send Message", "Member", new {id=item.UserId}, new { onclick = "alert('This is not implemented yet',)"} )
                        </td>
                    </tr>
                }

            </table>
        </td>
    </tr>
</table>

AgiSoft/Views/Team/MemberTeams.cshtml
@model AgiSoft.Models.TeamViewModel

@{
    ViewBag.Title = "MemberTeams";
}

<h2>MemberTeams</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TeamViewModel</legend>

        <div>
            @Html.LabelFor(model => model.TeamNm)
        </div>
        <div>
            @Html.DisplayFor(model => model.TeamNm)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MemNm)
        </div>
        <div class="editor-field">
            <select>
                @foreach (AgiSoft.Models.UserProfile u in Model.Member) {
                    <option value="@u.UserId">@u.UserName</option>
                }                
            </select>
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AgiSoft/Views/Team/TeamProject.cshtml
@model AgiSoft.Models.TeamOnProject
@{
    ViewBag.Title = "TeamProject";
}

<h2>TeamProject</h2>
<nav>
    <ul id="menu">
        <li>@Html.ActionLink("Index", "Index", "Team")</li>
        <li>@Html.ActionLink("Member", "Member", "Team")</li>
        <li>@Html.ActionLink("Team Projects", "TeamProject", "Team")</li>
        <li>@Html.ActionLink("Assignments", "Assignment", "Team")</li>
    </ul>
</nav>

This page wilAgi be to view more detailed information concerning projects under particular team

AgiSoft/Views/Team/TeamsDetails.cshtml
@model AgiSoft.Models.Teams

@{
    ViewBag.Title = "TeamDetails";
}

@if (ViewBag.Type == "team") {
    <p>Test results are team</p>
    
    <h2>TeamDetails</h2>

    <fieldset>
        <legend>Team</legend>

        <div class="display-label">
             @Html.DisplayNameFor(model => model.TeamName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.TeamDesc)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Edit", "TeamsEdit", new { id=Model.TeamId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}